# 服务网关配置
spring:
  #redis配置
  redis:
    host: ${base.redis.host}
    port: ${base.redis.port}
    password: ${base.redis.password}
    database: 0

# 路由配置
zuul:
  retryable: true
  #　忽略所有默认路由
  ignored-services: '*'
  # 需要聚合的swagger服务
  swagger:
    serviceIds: taroco-rbac-service

security:
  validate:
    code: true
    preview: true
  sessions: stateless
  oauth2:
    client:
      client-id: taroco
      client-secret: taroco
    resource:
      jwt:
         key-uri: ${base.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

ignore:
  urls:
    - /actuator/**
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/menu/userMenu
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
  clients:
    - app
